import type { ParkingSpot } from "@/lib/firestore";

export type PublicParkingSpot = ParkingSpot & { id: string };

const DEFAULT_SCHEDULE: ParkingSpot["availability_schedule"] = {
  monday: { open: "06:00", close: "23:59" },
  tuesday: { open: "06:00", close: "23:59" },
  wednesday: { open: "06:00", close: "23:59" },
  thursday: { open: "06:00", close: "23:59" },
  friday: { open: "06:00", close: "23:59" },
  saturday: { open: "06:00", close: "23:59" },
  sunday: { open: "06:00", close: "23:59" },
};

export const PUBLIC_PARKING_SPOTS: PublicParkingSpot[] = [
  {
    id: "public-hyd-001",
    name: "Tank Bund Public Parking",
    address: "Tank Bund Road, Hyderabad",
    location: { lat: 17.4239, lng: 78.4747 },
    vendor_id: "public-system",
    type: "municipal",
    vehicle_types: ["bike", "car", "suv"],
    pricing: { flat_rate: 30, hourly_rate: 40 },
    total_spots: 120,
    current_occupancy: 54,
    status: "open",
    is_approved: true,
    trust_score: 82,
    rating: 4.2,
    review_count: 214,
    amenities: ["CCTV", "24/7"],
    images: [],
    availability_schedule: DEFAULT_SCHEDULE,
    conflict_flag: false,
  },
  {
    id: "public-hyd-002",
    name: "Koti Metro Public Lot",
    address: "Koti Main Road, Hyderabad",
    location: { lat: 17.3877, lng: 78.4853 },
    vendor_id: "public-system",
    type: "municipal",
    vehicle_types: ["bike", "car"],
    pricing: { flat_rate: 20, hourly_rate: 35 },
    total_spots: 95,
    current_occupancy: 28,
    status: "open",
    is_approved: true,
    trust_score: 79,
    rating: 4.0,
    review_count: 163,
    amenities: ["CCTV", "Covered"],
    images: [],
    availability_schedule: DEFAULT_SCHEDULE,
    conflict_flag: false,
  },
  {
    id: "public-hyd-003",
    name: "Charminar Civic Parking",
    address: "Near Charminar Bus Stop, Hyderabad",
    location: { lat: 17.3616, lng: 78.4747 },
    vendor_id: "public-system",
    type: "roadside",
    vehicle_types: ["bike", "car"],
    pricing: { flat_rate: 25, hourly_rate: 30 },
    total_spots: 80,
    current_occupancy: 62,
    status: "open",
    is_approved: true,
    trust_score: 74,
    rating: 3.8,
    review_count: 142,
    amenities: ["Security"],
    images: [],
    availability_schedule: DEFAULT_SCHEDULE,
    conflict_flag: false,
  },
  {
    id: "public-hyd-004",
    name: "Hitec City Public Plaza Parking",
    address: "Madhapur Main Junction, Hyderabad",
    location: { lat: 17.4504, lng: 78.3808 },
    vendor_id: "public-system",
    type: "municipal",
    vehicle_types: ["bike", "car", "suv"],
    pricing: { flat_rate: 40, hourly_rate: 55 },
    total_spots: 160,
    current_occupancy: 84,
    status: "open",
    is_approved: true,
    trust_score: 87,
    rating: 4.4,
    review_count: 301,
    amenities: ["CCTV", "Covered", "EV Charging"],
    images: [],
    availability_schedule: DEFAULT_SCHEDULE,
    conflict_flag: false,
  },
  {
    id: "public-hyd-005",
    name: "Secunderabad Station Public Deck",
    address: "Secunderabad Railway Station, Hyderabad",
    location: { lat: 17.4399, lng: 78.4983 },
    vendor_id: "public-system",
    type: "municipal",
    vehicle_types: ["bike", "car", "suv"],
    pricing: { flat_rate: 35, hourly_rate: 45 },
    total_spots: 140,
    current_occupancy: 106,
    status: "open",
    is_approved: true,
    trust_score: 81,
    rating: 4.1,
    review_count: 287,
    amenities: ["CCTV", "24/7", "Covered"],
    images: [],
    availability_schedule: DEFAULT_SCHEDULE,
    conflict_flag: false,
  },
  {
    id: "public-hyd-006",
    name: "Nampally Public Smart Parking",
    address: "Nampally Exhibition Grounds, Hyderabad",
    location: { lat: 17.3936, lng: 78.4666 },
    vendor_id: "public-system",
    type: "municipal",
    vehicle_types: ["bike", "car", "suv"],
    pricing: { flat_rate: 30, hourly_rate: 42 },
    total_spots: 110,
    current_occupancy: 35,
    status: "open",
    is_approved: true,
    trust_score: 85,
    rating: 4.3,
    review_count: 189,
    amenities: ["CCTV", "EV Charging", "24/7"],
    images: [],
    availability_schedule: DEFAULT_SCHEDULE,
    conflict_flag: false,
  },
];
